# Generated by Django 3.2.4 on 2021-07-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_rename_varify_profile_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
    ]
